### ISSUE TITLE
Add a new `api_updates` section

### ISSUE THREAD

**Issue by juangirini** [paritytech/prdoc#1]
As I am working in this PR https://github.com/paritytech/polkadot-sdk/pull/1226 that introduces a breaking change on existing dispatchables for external builders. I don't see how this would fit in the current schema.

We could probably have a new `api_updates` section were we can communicate this kind breaking changes.

And example would be something like
```
title: example

doc:
  - audience: Builders
    description: blah blah
    
api_updates
  - added: some new features
  - changed: something changed
  - removed: something that is no longer valid

migrations: []

crates:
  - name: something

host_functions: []
```

**Comment by chevdor** [comment]
What about the following (currently supported):
```
# Schema: Parity PR Documentation Schema (prdoc)

doc:
  - audience: Builder
    description: |
      - added: some new features
      - changed: something changed
      - removed: something that is no longer valid

migrations:
  db: []

  runtime: []

crates:
   - name: something

host_functions: []
```

**Comment by chevdor** [comment]
btw, it was created using: `prdoc generate 1226 --save`.
The above can be checked with: 
```
$ prdoc check -n 1226
PR #1226 -> OK 
```

**Comment by juangirini** [comment]
> What about the following (currently supported):

Yes, this is alright, I just thought that as api changes (specially breaking ones) are important to builders the deserved their own section. But I am happy with your proposal too.

**Comment by chevdor** [comment]
The plan with the current option is that `description` is rather open to the content you find appropriate.
It can be a simple sentence, several paragraphs, a list... We can probably use fully ledged markdown here and this text/content needs to be "tuned" to the audiance.

The rest of the document is more factual, for instance, if you introduce a breaking change in a crate, it will be breaking for everyone, not just for a specific audience.  Based on the templates, we can however decide to show (or not) some details to specific audiences.

The `crates` section however, allows providing more details on what is breaking or not. This is factual.
It sounds more like what you are after.

If you look at [this section](https://github.com/paritytech/prdoc/blob/master/schema_user.json#L85-L98), you see a `semver` field that is indended to provide such information.

This may or maybe not be assisted by some tooling in the future and I think we need to see how usable and accurate it can be for a prdoc authors. 

Thank you for your "example" btw, we need more of those to battle test the current schema and confirm that it is good enough to get started. If you have some more, please let me know.

**Comment by chevdor** [comment]
btw, you could also do:
```
# Schema: Parity PR Documentation Schema (prdoc)

doc:
  - audience: Builder
    description: |
      ## API updates
      - added: some new features
      - changed: something changed
      - removed: something that is no longer valid

migrations:
  db: []

  runtime: []

crates:
   - name: something

host_functions: []
```
