### ISSUE TITLE
Enforce specifying the bump type alongside the name of the crate being bumped

### ISSUE THREAD

**Issue by liamaharon** [paritytech/prdoc#29]
e.g. instead of writing

```
crates: 
  - name: pallet-balances
  - name: sp-io
  - name: remote-externalities
```

you'd write something like

```
crates:
  - pallet-balances minor
  - sp-io patch
  - remote-externalities major
```

Where the bump type can be `major` `minor` or `patch`.

This will be a key part of maintaining correct semver bumps once we switch to the new release process with stable/prerelease branches.
