### ISSUE TITLE
Feat req: DRY to target multiple `audience` with a common description

### ISSUE THREAD

**Issue by nuke-web3** [paritytech/prdoc#6]
I don't always want to explicitly tell every audience something different, sometimes I want to tell most or all audiences some of the same thing, and then further details explicitly for some subset or single audience.

**Comment by nuke-web3** [comment]
Maybe we want to use a new required overall `description` field and make `audience` optional completely. So everyone can see the "blanket" detials, and audiences can be specified to know _more_ info or nuance about it.

For example:

```yml
doc:
- description: This changes ... so that every existing account has 1 DOT minted to it 🤑

- audience: Core Dev
  description: This is an `Unbalanced` fungible operation, cause we wanna screw up accounting 🙈
```
